apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Docker 내부 네트워크로 Prometheus 연결
    isDefault: true              # 기본 데이터소스로 설정
    editable: true # yml에서 프로비저닝하면 데이터소스가 잠기지만 UI에서도 수정 가능하게
