spring:
  datasource:
    url: jdbc:h2:mem:fitme;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # HikariCP 튜닝(local 에서 테스트해볼때 쓸것)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 1800000
  h2:
    console:
      enabled: on
      path: /h2-console
      settings:
        web-allow-others: true # NOTE: docker 컨테이너 내부 앱이기때문에 브라우저로 접근시 localhost:8080으로 허용해준건 컨테이너 내부인거고 외부접근은 허용되지않았기때문에 이렇게 해줘야함
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: broker:29092

  cache:
    type: caffeine
    redis:
      enable-statistics: true

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.ootd: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    caches:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
  observations:
    annotations:
      enabled: true

fitme:
  storage:
    type: local  # <= 여기 값이 'local'일 때만 LocalBinaryContentStorage를 빈으로 등록, s3 이면 S3BinaryContentStorage 빈 등록
    local:
      root-path: ./storage # 로컬환경 프로젝트 루트에서 /storage 로사용

server:
  port: 8080 # local의 경우 이제 도커 컴포즈로 기본 실행하면 8080을 사용하기때문에 충돌방지를 위해 Local은 8081, 추후 Nginx로 사용시 도커 8080 port안쓸때는 8080으로 수정