spring:
  datasource:
    url: jdbc:h2:mem:fitme;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # HikariCP 튜닝(local 에서 테스트해볼때 쓸것)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 1800000
  h2:
    console:
      enabled: on
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate

  kafka: # NOTE: 현재 카프카 사용은 안하지만 미리 세팅 추후 사용할때 참고
    bootstrap-servers: localhost:9092

  cache:
    type: caffeine
    redis:
      enable-statistics: true

  data:
    redis:
      host: localhost
      port: 6380

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.ootd: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    caches:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
  observations:
    annotations:
      enabled: true

fitme:
  storage:
    type: local  # <= 여기 값이 'local'일 때만 LocalBinaryContentStorage를 빈으로 등록, s3 이면 S3BinaryContentStorage 빈 등록
    local:
      root-path: ./storage # 로컬환경 프로젝트 루트에서 /storage 로사용
