spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # HikariCP 튜닝
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      max-lifetime: 1800000


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # (중복 제거) 운영에선 validate 필수
    properties:
      hibernate:
        default_batch_fetch_size: 100 # (덮어쓰기) Prod는 성능 위해 100으로 증가

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} # ex) my-namespace.servicebus.windows.net:9093
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="$ConnectionString"
        password="${EVENT_HUBS_CONNECTION_STRING}";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  elasticsearch:
    uris: ${ELASTICSEARCH_URI}

logging:
  level:
    com.ootd: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: error

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, caches # (보안) Prod는 * 대신 필요한 것만 노출
  endpoint:
    health:
      show-details: always # (보안) 운영서버지만 초기에 잘 뜨는지 확인하기위해 always설정 추후 when_authorized 변경 고려
      show-components: always

  health:
    elasticsearch:
      enabled: true

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration-ms: 900000      # 15분
  refresh-token-expiration-ms: 1209600000 # 2주
  issuer: fitme

admin:
  bootstrap:
    enabled: true
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    profile-name: ${ADMIN_PROFILE_NAME}
    reset-password: false