spring:
  application:
    name: fitme
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        type:
          preferred_instant_jdbc_type: TIMESTAMP_WITH_TIMEZONE
        order_inserts: true
        order_updates: true
        jdbc:
          time_zone: UTC
          batch_size: 50
    open-in-view: false

  batch:
    job:
      enabled: false

  storage:
    type: azure # 기본 application, -prod 에서 azure를 쓰도록 하고 만약 자신이 Local을 쓰고싶다면 -local 에서 local로 사용테스트
    app:
      azure:
        cdn:
          domain: https://your-cdn-endpoint.azureedge.net
        credentials:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
        log-credentials:
          account-name: ${AZURE_LOG_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_LOG_STORAGE_ACCOUNT_KEY}
        region:
          static: koreacentral
        blob:
          container: fitme-v1-container
          log-container: wardrobe-v1-log-container

# prod제외 모든 환경에서 환경변수 값으로 동적이거나 보안적으로 가릴 필요없기때문에 공통적인 값은 그대로 쓰는방식, Prod에서만 환경변수로 오버라이딩 처리
jwt:
  secret-key: mySecretKeyForJwtTokenGeneration1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  access-token-expiration-ms: 900000      # 15분
  refresh-token-expiration-ms: 1209600000 # 2주
  issuer: fitme


logging:
  level:
    root: info

external:
  kakao:
    rest-api-key: ${KAKAO_API_KEY}
    local:
      base-url: https://dapi.kakao.com
      coord2region-path: /v2/local/geo/coord2regioncode.json

  openweather:
    rest-api-key: ${OPEN_WEATHER_API_KEY}
    base-url: https://api.openweathermap.org
    forecast-path: /data/2.5/forecast

# 운영 Prod에서 오버라이딩 할예정이라 그대로 씀
admin:
  bootstrap:
    enabled: true
    email: admin@test.com
    password: admin123!
    profile-name: admin
    reset-password: false

security:
  cors:
    allowed-origins: http://localhost:8080