global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fitme-app'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['fitme-app.internal.mangofield-4b56edf3.koreacentral.azurecontainerapps.io']